### ISSUE TITLE
`_tide_item_status` errors when the last command contains a pipe

### ISSUE THREAD

**Issue by 9999years** [IlanCosman/tide#331]
#### Describe the bug

When there are multiple statuses from the last command (for example, when running `echo hello | cat`), `_tide_item_status` errors trying to parse multiple statuses (like `0 0`) as one integer.

#### Steps to reproduce

1. (I think) make sure `$tide_right_prompt_items` contains `$status`. (Probably could be left prompt too.)
2. Run `echo hello | cat`
3. See error:M

```
Integer 0 in '0 0' followed by non-digit
/opt/homebrew/Cellar/fish/3.5.1/share/fish/functions/fish_status_to_signal.fish (line 4):
        if test $arg -gt 128
           ^
in function 'fish_status_to_signal' with arguments '0\ 0'
        called on line 7 of file ~/.config/fish/fundle/IlanCosman/tide/functions/_tide_item_status.fish
in function '_tide_item_status'
        called on line 15 of file ~/.config/fish/fundle/IlanCosman/tide/functions/_tide_2_line_prompt.fish
in function '_tide_2_line_prompt'
```

#### Environment

Output of `tide bug-report`: 

```yaml
fish version:      3.5.1
tide version:      5.4.0
term:              screen-256color
os:                macOS Monterey 12.5.1
terminal emulator: iTerm2
fish startup:      43.01 millis
fisher plugins:    franciscolourenco/done jethrokuan/fzf edc/bass oh-my-fish/plugin-sudope IlanCosman/tide@v5 jethrokuan/z
```
